export const colors = {
  bgPrimary: '#FFFFFF',
  bgSection: '#F2F8FA',
  bgSecondary: '#F2F8FA',
  bgSurface: '#FFFFFF',
  bgCard: '#FFFFFF',
  textPrimary: '#0A2840',
  textSecondary: '#1A4A6E',
  textMuted: '#6A8898',
  textAccent: '#0A7B8A',
  borderDefault: '#C8E0E8',
  borderFocus: '#0A7B8A',
  borderError: '#C0392B',
  brandPrimary: '#0A7B8A',
  statusSuccess: '#2E7D30',
  statusWarning: '#f59e0b',
  statusError: '#C0392B',
  statusInfo: '#3b82f6',
  white: '#ffffff',
} as const;
